--- #YAML:1.0
name:               Catalyst-ActionRole-MatchHost
version:            0.03
abstract:           Match action against domain host name
author:
    - Anatoliy Lapitskiy <nuclon@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Controller::ActionRole:  0
    Catalyst::Runtime:    5.80
    Moose::Role:          0
    namespace::autoclean:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
